#!/usr/bin/env python

import getpass
import argparse
import sys
import os

import lib.crypto as crypto
import lib.cfg as cfg
import lib.log as log

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Create empty cryptobox database')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + cfg.version)
    parser.add_argument('-V', '--verbose', action='count')
    cfg.init(parser.parse_args())

    try:
        os.mkdir(cfg.path_private + "/")
    except:
        pass

    if os.path.exists(cfg.path_db):
        ans = log.yn("File '%s' already exists, do you want to overwrite it?" % cfg.path_db)

        if not ans in ['Y', 'y']:
            sys.exit(0)

    password = getpass.getpass('Password: ')
    password2 = getpass.getpass('Retype password: ')

    if password != password2:
        log.e("Your passwords don't match!")
        sys.exit(0)

    crypto.create_cfg(cfg.path_cfg)
    conf = crypto.read_cfg(cfg.path_cfg)
    crypto.enc_plaintext(conf, password, "# Lines started with # are comments", cfg.path_db, cfg.path_db_hmac)
