#!/usr/bin/env python

import tempfile
import subprocess
import os
import getpass

import lib.crypto
import lib.cfg
import lib.html

if __name__ == "__main__":
    password = getpass.getpass()

    plaintext = lib.crypto.dec_db(password, lib.cfg.path_db, lib.cfg.path_db_hmac)

    EDITOR = os.environ.get('EDITOR', lib.cfg.editor)

    with tempfile.NamedTemporaryFile(delete=False) as f:
        file_name = f.name
        f.write(plaintext.encode('utf-8'))
        f.flush()

    mtime_begin = os.stat(file_name).st_mtime
    subprocess.call([EDITOR, "--", file_name])
    mtime_end = os.stat(file_name).st_mtime

    if mtime_begin != mtime_end:
        lib.crypto.enc_db(password, file_name, lib.cfg.path_db, lib.cfg.path_db_hmac)
        lib.html.update(password)
    else:
        print "No update to database"

    os.remove(file_name)
