#!/usr/bin/env python

import tempfile
import subprocess
import os
import getpass
import argparse
import sys

import lib.crypto as crypto
import lib.cfg as cfg
import lib.html as html
import lib.log as log

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Edit cryptobox database')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + cfg.version)
    parser.add_argument('-V', '--verbose', action='count')
    cfg.init(parser.parse_args())

    password = getpass.getpass()

    conf = crypto.read_cfg(cfg.path_cfg)
    plaintext = crypto.dec_db(conf, password, cfg.path_db, cfg.path_db_hmac)

    EDITOR = os.environ.get('EDITOR', cfg.editor)

    with tempfile.NamedTemporaryFile(suffix='.ini', delete=False) as f:
        file_name = f.name
        f.write(plaintext.encode('utf-8'))
        f.flush()

    mtime_begin = os.stat(file_name).st_mtime
    subprocess.call([EDITOR, "--", file_name])
    mtime_end = os.stat(file_name).st_mtime

    if mtime_begin != mtime_end:
        try:
            cfg.backup()
        except:
            ans = log.yn("Couldn't perform a backup, continue?")

            if not ans in ['Y', 'y']:
                sys.exit(0)

        crypto.enc_db(conf, password, file_name, cfg.path_db, cfg.path_db_hmac)
        html.update(conf, password)
    else:
        log.p("No update to database")

    os.remove(file_name)
