#!/usr/bin/env python

import getpass
import argparse

import lib.html as html
import lib.crypto as crypto
import lib.cfg as cfg

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Update HTML pages')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + cfg.version)
    parser.add_argument('-V', '--verbose', action='count')
    cfg.init(parser.parse_args())

    password = getpass.getpass()

    db_conf = crypto.read_db_conf(cfg.path['db_conf'])
    html.update(db_conf, password)
