#!/usr/bin/env python

import getpass
import argparse

from lib.generate import generate_all
from lib.crypto import read_db_conf
import lib.cfg as cfg

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Update HTML pages')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + cfg.version)
    parser.add_argument('-V', '--verbose', action='count', help='enable verbose mode')
    parser.add_argument('-c', '--config', action='store', help='use specified config')
    cfg.init(parser.parse_args())

    password = getpass.getpass()

    db_conf = read_db_conf(cfg.path['db_conf'], cfg.format_version)
    generate_all(db_conf, password)
