#!/usr/bin/env python

import getpass
import argparse

import lib.html
import lib.cfg

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Update HTML pages')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + lib.cfg.version)
    parser.parse_args()

    password = getpass.getpass()

    lib.html.update(password)
