#!/usr/bin/env python

import getpass
import argparse
import sys

import lib.crypto as crypto
import lib.cfg as cfg
import lib.log as log

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Change master password')
    parser.add_argument('-v', '--version', action='version', version='Cryptobox ' + cfg.version)
    parser.add_argument('-V', '--verbose', action='count')
    cfg.init(parser.parse_args())

    password = getpass.getpass('Current password: ')

    new_password = getpass.getpass('New password: ')
    new_password2 = getpass.getpass('Retype new password: ')

    if new_password != new_password2:
        log.e("Your passwords don't match!")
        sys.exit(0)

    try:
        cfg.backup()
    except:
        ans = log.yn("Couldn't perform a backup, continue?")

        if not ans in ['Y', 'y']:
            sys.exit(0)

    conf = crypto.read_cfg(cfg.path_cfg)
    plaintext = crypto.dec_db(conf, password, cfg.path_db, cfg.path_db_hmac)
    crypto.enc_plaintext(conf, new_password, plaintext, cfg.path_db, cfg.path_db_hmac)
