#!/usr/bin/env python

import getpass

import lib.flatten
import lib.crypto
import lib.generate
import lib.embed
import lib.html

if __name__ == "__main__":
    password = getpass.getpass()

    lib.html.update(password)
